server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/digixo
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: product
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

rabbitmq:
  exchange: product-exchange
  routing-key: product.notification.routing-key