server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/digixo
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: product
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

rabbitmq:
  exchange: product-exchange
  routing-key: product.notification.routing-key

resilience4j:
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 100
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
  ratelimiter:
    configs:
      default:
        limit-refresh-period: 20000
        limit-for-period: 5
        timeout-duration: 1
