server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/digixo
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: product
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka