server:
  port: 8761

spring:
  application:
    name: eureka
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    response-cache-update-interval-ms: 5000
    wait-time-in-ms-when-sync-empty: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    gateway:
      enabled: true
    health:
      show-details: always
  info:
    env:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}