server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://postgres:5432/digixo
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: discount
eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    info:
      enabled: true
    gateway:
      enabled: true
    health:
      show-details: always
  info:
    env:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
